In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/loan_risk_dataset_corrupted.csv")
print("Shape :",df.shape)
df.head()

Shape : (25750, 35)

,Unnamed: 0,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,...,MissedEMIs,BankBalance,PropertyValue,Dependents,Region,CityTier,PreviousDefaults,FraudFlag,CustomerSegment,LoanApproved
0,0,112424,36,Male,Single,PostGraduate,Salaried,25.0,6114208.0,190034,...,3,79209.0,46730799.0,4,East,Tier3,1,No,Regular,No
1,1,108271,25,Female,Single,HighSchool,SelfEmployed,30.0,4487423.0,24602,...,2,517042.0,15261353.0,0,West,Tier2,1,No,Regular,Yes
2,2,122724,32,Male,Single,Graduate,SelfEmployed,8.0,7493921.0,60028,...,4,1956071.0,39629890.0,4,North,Tier1,0,No,Regular,Yes
3,3,112573,30,Female,Married,Graduate,Student,35.0,NaN,187520,...,3,912949.0,14425719.0,0,East,Tier3,2,No,Regular,Yes
4,4,112098,41,Female,Single,Graduate,Business,36.0,7929802.0,199257,...,3,NaN,43000549.0,4,North,Tier2,2,No,Regular,No

In [3]:
type(df)

pandas.DataFrame

In [4]:
df = df.drop(columns=["Unnamed: 0"])

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25750 entries, 0 to 25749
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerID            25750 non-null  int64
 1   Age                   25750 non-null  int64
 2   Gender                25750 non-null  str
 3   MaritalStatus         25750 non-null  str
 4   Education             23941 non-null  str
 5   Occupation            23932 non-null  str
 6   EmploymentYears       23957 non-null  float64
 7   AnnualIncome          23250 non-null  float64
 8   MonthlyExpenses       25750 non-null  int64
 9   Savings               23964 non-null  float64
 10  Investments           25750 non-null  int64
 11  ExistingLoans         25750 non-null  int64
 12  ExistingEMI           25750 non-null  int64
 13  LoanAmount            23957 non-null  float64
 14  LoanPurpose           25750 non-null  str
 15  LoanTenure            25750 non-null  int64
 16  CreditScore           23972 non-null  float64
 17  CreditCardLimit       25750 non-null  int64
 18  CreditCardUsage       25750 non-null  int64
 19  CreditUtilization     25750 non-null  int64
 20  TransactionsPerMonth  25750 non-null  int64
 21  OnlineTransactions    25750 non-null  int64
 22  ATMWithdrawals        25750 non-null  int64
 23  LatePayments          25750 non-null  int64
 24  MissedEMIs            25750 non-null  int64
 25  BankBalance           23942 non-null  float64
 26  PropertyValue         23950 non-null  float64
 27  Dependents            25750 non-null  int64
 28  Region                25750 non-null  str
 29  CityTier              25750 non-null  str
 30  PreviousDefaults      25750 non-null  int64
 31  FraudFlag             25750 non-null  str
 32  CustomerSegment       25750 non-null  str
 33  LoanApproved          25750 non-null  str
dtypes: float64(7), int64(17), str(10)
memory usage: 6.7 MB

In [6]:
df.describe()

,CustomerID,Age,EmploymentYears,AnnualIncome,MonthlyExpenses,Savings,Investments,ExistingLoans,ExistingEMI,LoanAmount,...,CreditUtilization,TransactionsPerMonth,OnlineTransactions,ATMWithdrawals,LatePayments,MissedEMIs,BankBalance,PropertyValue,Dependents,PreviousDefaults
count,25750.000000,25750.000000,23957.000000,2.325000e+04,25750.000000,2.396400e+04,2.575000e+04,25750.000000,25750.000000,2.395700e+04,...,25750.000000,25750.000000,25750.000000,25750.000000,25750.000000,25750.000000,2.394200e+04,2.395000e+04,25750.000000,25750.000000
mean,112490.685320,42.643961,19.895020,4.409589e+06,129435.114097,5.442453e+06,2.495241e+06,2.488971,60090.737087,2.611708e+06,...,49.654680,151.967767,99.467456,11.991961,5.467767,2.487806,1.001433e+06,2.483399e+07,2.497903,1.511340
std,7216.676586,13.353262,11.791488,4.124029e+06,69297.117136,6.257410e+06,1.445536e+06,1.707519,34666.475712,1.887419e+06,...,29.255941,85.303556,57.785347,7.217996,3.464969,1.703390,5.772066e+05,1.446552e+07,1.714748,1.117373
min,100001.000000,-5.000000,0.000000,1.805250e+05,10029.000000,2.950000e+02,8.400000e+01,0.000000,0.000000,-1.000000e+05,...,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,2.060000e+02,1.900000e+02,0.000000,0.000000
25%,106244.250000,32.000000,10.000000,2.182536e+06,69463.000000,2.495756e+06,1.235423e+06,1.000000,30308.000000,1.269556e+06,...,24.000000,79.000000,49.000000,6.000000,2.000000,1.000000,5.021138e+05,1.216278e+07,1.000000,1.000000
50%,112477.500000,43.000000,20.000000,4.152555e+06,129289.500000,5.001134e+06,2.500821e+06,2.000000,59733.000000,2.540088e+06,...,49.000000,152.000000,100.000000,12.000000,5.000000,2.000000,9.995985e+05,2.478683e+07,2.000000,2.000000
75%,118741.750000,54.000000,30.000000,6.106680e+06,189351.250000,7.521484e+06,3.744196e+06,4.000000,90342.500000,3.795003e+06,...,75.000000,225.000000,149.000000,18.000000,8.000000,4.000000,1.504992e+06,3.743326e+07,4.000000,3.000000
max,125000.000000,65.000000,40.000000,6.395999e+07,249967.000000,9.987491e+07,4.999975e+06,5.000000,119995.000000,2.476599e+07,...,100.000000,299.000000,199.000000,24.000000,11.000000,5.000000,1.999920e+06,4.999978e+07,5.000000,3.000000

In [7]:
df.describe(include="object")

C:\Users\Pranavraj\AppData\Local\Temp\ipykernel_22924\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Gender,MaritalStatus,Education,Occupation,LoanPurpose,Region,CityTier,FraudFlag,CustomerSegment,LoanApproved
count,25750,25750,23941,23932,25750,25750,25750,25750,25750,25750
unique,2,3,4,5,6,4,3,2,3,2
top,Male,Married,Graduate,Salaried,Medical,East,Tier2,No,Regular,Yes
freq,13017,14054,10816,10722,4369,6450,8638,24497,15018,18980

In [8]:
missing = df.isnull().sum()

missing = missing[missing > 0]

missing.sort_values(ascending=False)

AnnualIncome       2500
Occupation         1818
Education          1809
BankBalance        1808
PropertyValue      1800
LoanAmount         1793
EmploymentYears    1793
Savings            1786
CreditScore        1778
dtype: int64

In [9]:
duplicates = df.duplicated().sum()
print("Duplicate Rows :",duplicates)

Duplicate Rows : 150

In [10]:
df[df["Age"] < 18]

,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,Savings,...,MissedEMIs,BankBalance,PropertyValue,Dependents,Region,CityTier,PreviousDefaults,FraudFlag,CustomerSegment,LoanApproved
15,102387,-5,Male,Married,Graduate,Salaried,17.0,7737226.0,216639,8257679.0,...,2,NaN,38137996.0,3,North,Tier2,0,No,Premium,Yes
148,114544,-5,Female,Married,HighSchool,Salaried,12.0,2935520.0,145795,8294950.0,...,5,1743180.0,35844100.0,0,East,Tier3,3,No,Regular,No
169,102534,-5,Female,Married,Graduate,NaN,19.0,NaN,174250,8655700.0,...,0,1800465.0,25078219.0,3,South,Tier1,0,No,Regular,Yes
477,124036,-5,Female,Single,NaN,Salaried,0.0,6633080.0,249460,4486310.0,...,4,104179.0,16842454.0,3,East,Tier2,3,No,Regular,No
513,122072,-5,Male,Married,Graduate,Student,21.0,7110798.0,248125,5813283.0,...,5,1377975.0,49592855.0,5,South,Tier3,2,No,Regular,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25016,122701,-5,Female,Married,PostGraduate,Business,16.0,5990612.0,37048,9492718.0,...,0,1224579.0,29144779.0,1,West,Tier1,3,No,Premium,Yes
25340,107456,-5,Male,Married,HighSchool,NaN,2.0,817532.0,215259,965269.0,...,2,106954.0,16690569.0,2,West,Tier3,0,No,Regular,No
25395,114374,-5,Male,Married,NaN,Salaried,18.0,6551114.0,193556,5023130.0,...,3,1147380.0,8994196.0,1,South,Tier2,3,No,Regular,Yes
25447,107159,-5,Female,Married,PostGraduate,Business,26.0,7021642.0,228280,9910288.0,...,5,779625.0,39200905.0,3,West,Tier1,0,Yes,Risky,No
25591,119175,-5,Female,Married,PostGraduate,NaN,6.0,5688163.0,226522,656138.0,...,1,912046.0,12665211.0,0,South,Tier2,3,No,Premium,Yes

In [11]:
df[df["CreditScore"] > 900]

,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,Savings,...,MissedEMIs,BankBalance,PropertyValue,Dependents,Region,CityTier,PreviousDefaults,FraudFlag,CustomerSegment,LoanApproved
136,103705,33,Female,Single,Graduate,SelfEmployed,8.0,NaN,117347,507314.0,...,0,545001.0,5143951.0,0,South,Tier3,0,No,Regular,Yes
224,105655,30,Female,Married,HighSchool,Salaried,14.0,2154585.0,156532,1722219.0,...,1,1690722.0,40913261.0,0,North,Tier1,1,No,Regular,Yes
256,108616,26,Male,Married,PostGraduate,SelfEmployed,NaN,3952248.0,114531,9623800.0,...,0,1155534.0,47893324.0,5,East,Tier3,3,No,Regular,Yes
365,109721,32,Female,Married,PostGraduate,Salaried,34.0,4171604.0,18058,1443430.0,...,3,168997.0,15989548.0,5,North,Tier2,3,No,Regular,Yes
496,121706,34,Male,Married,Graduate,NaN,NaN,4655111.0,115381,1339424.0,...,3,1906160.0,18358161.0,1,South,Tier2,3,No,Regular,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24967,124276,33,Male,Married,PostGraduate,SelfEmployed,30.0,1879620.0,137004,5564828.0,...,3,1033709.0,4416575.0,1,North,Tier1,2,No,Regular,Yes
25337,118071,36,Male,Married,PostGraduate,Business,2.0,5794518.0,21593,6786948.0,...,1,1496429.0,1033764.0,1,North,Tier1,1,No,Premium,Yes
25361,111754,41,Male,Single,PostGraduate,Salaried,30.0,NaN,183789,4490084.0,...,2,1830994.0,34630406.0,3,East,Tier1,0,No,Regular,Yes
25374,123724,53,Female,Divorced,Graduate,Student,0.0,2056152.0,173445,3294377.0,...,3,1949618.0,39847763.0,3,South,Tier3,3,Yes,Risky,No
25384,109152,26,Male,Married,Graduate,Salaried,23.0,2263101.0,189872,8458413.0,...,3,712231.0,37913442.0,3,West,Tier1,0,No,Premium,Yes

In [12]:
df[df["LoanAmount"] < 0]

,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,Savings,...,MissedEMIs,BankBalance,PropertyValue,Dependents,Region,CityTier,PreviousDefaults,FraudFlag,CustomerSegment,LoanApproved
306,115533,44,Male,Married,Graduate,Salaried,23.0,5792091.0,39307,1951352.0,...,2,1701502.0,88049.0,0,East,Tier3,3,No,Premium,Yes
538,114765,48,Female,Married,PostGraduate,Student,23.0,4013672.0,11106,NaN,...,2,1929424.0,5838317.0,5,South,Tier2,0,No,Premium,Yes
1145,118639,21,Female,Married,HighSchool,Retired,NaN,NaN,195565,5109654.0,...,4,321757.0,5290307.0,0,North,Tier2,3,No,Regular,Yes
1658,124468,60,Male,Divorced,Graduate,SelfEmployed,29.0,4224569.0,60835,125142.0,...,2,412998.0,9473615.0,0,North,Tier1,0,No,Regular,Yes
1910,120066,55,Male,Single,Graduate,Salaried,37.0,4629058.0,112620,454876.0,...,4,1371739.0,16600044.0,4,West,Tier3,2,No,Regular,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25282,122076,33,Female,Divorced,Graduate,SelfEmployed,28.0,7368126.0,115650,5456170.0,...,5,287621.0,10210180.0,0,South,Tier1,0,No,Regular,Yes
25334,116539,30,Male,Divorced,Graduate,SelfEmployed,8.0,3980453.0,177776,NaN,...,0,1449056.0,815025.0,2,East,Tier2,3,No,Premium,Yes
25350,124704,31,Male,Single,HighSchool,Business,34.0,5158516.0,202746,9548910.0,...,2,1087365.0,22303260.0,1,East,Tier2,3,No,Regular,Yes
25530,123939,54,Female,Married,Graduate,SelfEmployed,8.0,674634.0,248192,5837305.0,...,1,1918717.0,16129534.0,1,South,Tier2,0,No,Regular,Yes
25726,117569,45,Female,Married,Graduate,Salaried,6.0,7459904.0,186807,8233736.0,...,3,1594491.0,42467722.0,4,South,Tier2,3,No,Regular,No

In [13]:
for col in df.columns:
    print("="*50)
    print(col)
    print(df[col].nunique())

==================================================
CustomerID
25000
==================================================
Age
46
==================================================
Gender
2
==================================================
MaritalStatus
3
==================================================
Education
4
==================================================
Occupation
5
==================================================
EmploymentYears
41
==================================================
AnnualIncome
23216
==================================================
MonthlyExpenses
23755
==================================================
Savings
23248
==================================================
Investments
24936
==================================================
ExistingLoans
6
==================================================
ExistingEMI
22552
==================================================
LoanAmount
23095
==================================================
LoanPurpose
6
==================================================
LoanTenure
9
==================================================
CreditScore
602
==================================================
CreditCardLimit
24823
==================================================
CreditCardUsage
23004
==================================================
CreditUtilization
101
==================================================
TransactionsPerMonth
295
==================================================
OnlineTransactions
200
==================================================
ATMWithdrawals
25
==================================================
LatePayments
12
==================================================
MissedEMIs
6
==================================================
BankBalance
23105
==================================================
PropertyValue
23242
==================================================
Dependents
6
==================================================
Region
4
==================================================
CityTier
3
==================================================
PreviousDefaults
4
==================================================
FraudFlag
2
==================================================
CustomerSegment
3
==================================================
LoanApproved
2

In [16]:
df["LoanApproved"].value_counts()

LoanApproved
Yes    18980
No      6770
Name: count, dtype: int64

In [17]:
df["FraudFlag"].value_counts()

FraudFlag
No     24497
Yes     1253
Name: count, dtype: int64

In [18]:
df["CustomerSegment"].value_counts()

CustomerSegment
Regular    15018
Premium     9479
Risky       1253
Name: count, dtype: int64