In [10]:
import numpy as np
import pandas as pd

np.random.seed(42)

In [11]:
df = pd.read_csv("../data/raw/loan_risk_dataset.csv")

print("Original Shape:", df.shape)

df.head()

Original Shape: (25000, 34)

,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,Savings,...,MissedEMIs,BankBalance,PropertyValue,Dependents,Region,CityTier,PreviousDefaults,FraudFlag,CustomerSegment,LoanApproved
0,100001,59,Male,Divorced,Graduate,Student,34,1560590,205716,3317359,...,3,1969591,26713732,1,North,Tier1,0,No,Regular,No
1,100002,49,Female,Married,PostGraduate,Business,28,4264221,19625,924493,...,1,1834509,31344906,4,East,Tier3,0,No,Regular,No
2,100003,35,Female,Single,HighSchool,Salaried,32,7287119,92683,6428584,...,0,1108737,16185829,1,East,Tier1,3,No,Premium,Yes
3,100004,63,Female,Single,Graduate,Business,35,3676711,214164,4626067,...,4,1217452,13617947,4,North,Tier3,0,No,Regular,No
4,100005,28,Female,Divorced,PostGraduate,Salaried,6,4072754,241888,1526975,...,2,386923,14166809,5,West,Tier3,0,No,Premium,Yes

In [12]:
columns = [
    "AnnualIncome",
    "Savings",
    "CreditScore",
    "LoanAmount",
    "EmploymentYears",
    "Occupation",
    "Education",
    "PropertyValue",
    "BankBalance"
]
for col in columns:
    missing_index = df.sample(frac = 0.07).index
    df.loc[missing_index,col] = np.nan

In [13]:
df.isnull().sum()

CustomerID                 0
Age                        0
Gender                     0
MaritalStatus              0
Education               1750
Occupation              1750
EmploymentYears         1750
AnnualIncome            1750
MonthlyExpenses            0
Savings                 1750
Investments                0
ExistingLoans              0
ExistingEMI                0
LoanAmount              1750
LoanPurpose                0
LoanTenure                 0
CreditScore             1750
CreditCardLimit            0
CreditCardUsage            0
CreditUtilization          0
TransactionsPerMonth       0
OnlineTransactions         0
ATMWithdrawals             0
LatePayments               0
MissedEMIs                 0
BankBalance             1750
PropertyValue           1750
Dependents                 0
Region                     0
CityTier                   0
PreviousDefaults           0
FraudFlag                  0
CustomerSegment            0
LoanApproved               0
dtype: int64

In [14]:
duplicates = df.sample(frac=0.03, random_state=42)

df = pd.concat([df, duplicates], ignore_index=True)

print(df.shape)

(25750, 34)

In [15]:
income_index = df.sample(frac=0.01).index
df.loc[income_index, "AnnualIncome"] *= 8

saving_index = df.sample(frac=0.01).index
df.loc[saving_index, "Savings"] *= 10

loan_index = df.sample(frac=0.01).index
df.loc[loan_index, "LoanAmount"] *= 5

In [16]:
noise = np.random.randint(-2, 3, len(df))

df["Age"] = df["Age"] + noise

df["Age"] = df["Age"].clip(21, 65)

In [17]:
invalid_age = df.sample(frac=0.005).index
df.loc[invalid_age, "Age"] = -5

invalid_credit = df.sample(frac=0.005).index
df.loc[invalid_credit, "CreditScore"] = 1200

invalid_loan = df.sample(frac=0.005,random_state=7).index
df.loc[invalid_loan,"LoanAmount"] = -100000

In [18]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [19]:
df.to_csv("../data/processed/loan_risk_dataset_corrupted.csv")

In [20]:
print("Shape :", df.shape)

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows :", df.duplicated().sum())

df.head()

Shape : (25750, 34)

Missing Values
CustomerID                 0
Age                        0
Gender                     0
MaritalStatus              0
Education               1809
Occupation              1818
EmploymentYears         1793
AnnualIncome            2500
MonthlyExpenses            0
Savings                 1786
Investments                0
ExistingLoans              0
ExistingEMI                0
LoanAmount              1793
LoanPurpose                0
LoanTenure                 0
CreditScore             1778
CreditCardLimit            0
CreditCardUsage            0
CreditUtilization          0
TransactionsPerMonth       0
OnlineTransactions         0
ATMWithdrawals             0
LatePayments               0
MissedEMIs                 0
BankBalance             1808
PropertyValue           1800
Dependents                 0
Region                     0
CityTier                   0
PreviousDefaults           0
FraudFlag                  0
CustomerSegment            0
LoanApproved               0
dtype: int64

Duplicate Rows : 150

,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,Savings,...,MissedEMIs,BankBalance,PropertyValue,Dependents,Region,CityTier,PreviousDefaults,FraudFlag,CustomerSegment,LoanApproved
0,112424,36,Male,Single,PostGraduate,Salaried,25.0,6114208.0,190034,4591940.0,...,3,79209.0,46730799.0,4,East,Tier3,1,No,Regular,No
1,108271,25,Female,Single,HighSchool,SelfEmployed,30.0,4487423.0,24602,8884145.0,...,2,517042.0,15261353.0,0,West,Tier2,1,No,Regular,Yes
2,122724,32,Male,Single,Graduate,SelfEmployed,8.0,7493921.0,60028,4163611.0,...,4,1956071.0,39629890.0,4,North,Tier1,0,No,Regular,Yes
3,112573,30,Female,Married,Graduate,Student,35.0,NaN,187520,9707012.0,...,3,912949.0,14425719.0,0,East,Tier3,2,No,Regular,Yes
4,112098,41,Female,Single,Graduate,Business,36.0,7929802.0,199257,53335.0,...,3,NaN,43000549.0,4,North,Tier2,2,No,Regular,No