In [1]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv("../data/processed/loan_risk_dataset_corrupted.csv")

df.head()

,Unnamed: 0,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,...,MissedEMIs,BankBalance,PropertyValue,Dependents,Region,CityTier,PreviousDefaults,FraudFlag,CustomerSegment,LoanApproved
0,0,112424,36,Male,Single,PostGraduate,Salaried,25.0,6114208.0,190034,...,3,79209.0,46730799.0,4,East,Tier3,1,No,Regular,No
1,1,108271,25,Female,Single,HighSchool,SelfEmployed,30.0,4487423.0,24602,...,2,517042.0,15261353.0,0,West,Tier2,1,No,Regular,Yes
2,2,122724,32,Male,Single,Graduate,SelfEmployed,8.0,7493921.0,60028,...,4,1956071.0,39629890.0,4,North,Tier1,0,No,Regular,Yes
3,3,112573,30,Female,Married,Graduate,Student,35.0,NaN,187520,...,3,912949.0,14425719.0,0,East,Tier3,2,No,Regular,Yes
4,4,112098,41,Female,Single,Graduate,Business,36.0,7929802.0,199257,...,3,NaN,43000549.0,4,North,Tier2,2,No,Regular,No

In [5]:
df = df.drop(columns=["Unnamed: 0"])

In [6]:
df.duplicated().sum()

np.int64(150)

In [7]:
print("Before :",df.shape)

df = df.drop_duplicates()

print("After :",df.shape)

Before : (25750, 34)
After : (25600, 34)

In [8]:
df[df["Age"] < 18]

,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,Savings,...,MissedEMIs,BankBalance,PropertyValue,Dependents,Region,CityTier,PreviousDefaults,FraudFlag,CustomerSegment,LoanApproved
15,102387,-5,Male,Married,Graduate,Salaried,17.0,7737226.0,216639,8257679.0,...,2,NaN,38137996.0,3,North,Tier2,0,No,Premium,Yes
148,114544,-5,Female,Married,HighSchool,Salaried,12.0,2935520.0,145795,8294950.0,...,5,1743180.0,35844100.0,0,East,Tier3,3,No,Regular,No
169,102534,-5,Female,Married,Graduate,NaN,19.0,NaN,174250,8655700.0,...,0,1800465.0,25078219.0,3,South,Tier1,0,No,Regular,Yes
477,124036,-5,Female,Single,NaN,Salaried,0.0,6633080.0,249460,4486310.0,...,4,104179.0,16842454.0,3,East,Tier2,3,No,Regular,No
513,122072,-5,Male,Married,Graduate,Student,21.0,7110798.0,248125,5813283.0,...,5,1377975.0,49592855.0,5,South,Tier3,2,No,Regular,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25016,122701,-5,Female,Married,PostGraduate,Business,16.0,5990612.0,37048,9492718.0,...,0,1224579.0,29144779.0,1,West,Tier1,3,No,Premium,Yes
25340,107456,-5,Male,Married,HighSchool,NaN,2.0,817532.0,215259,965269.0,...,2,106954.0,16690569.0,2,West,Tier3,0,No,Regular,No
25395,114374,-5,Male,Married,NaN,Salaried,18.0,6551114.0,193556,5023130.0,...,3,1147380.0,8994196.0,1,South,Tier2,3,No,Regular,Yes
25447,107159,-5,Female,Married,PostGraduate,Business,26.0,7021642.0,228280,9910288.0,...,5,779625.0,39200905.0,3,West,Tier1,0,Yes,Risky,No
25591,119175,-5,Female,Married,PostGraduate,NaN,6.0,5688163.0,226522,656138.0,...,1,912046.0,12665211.0,0,South,Tier2,3,No,Premium,Yes

In [9]:
median_age = df[df["Age"] >= 18]["Age"].median()

df.loc[df["Age"] < 18,"Age"] = median_age

In [10]:
df[df["Age"] < 18]

Empty DataFrame
Columns: [CustomerID, Age, Gender, MaritalStatus, Education, Occupation, EmploymentYears, AnnualIncome, MonthlyExpenses, Savings, Investments, ExistingLoans, ExistingEMI, LoanAmount, LoanPurpose, LoanTenure, CreditScore, CreditCardLimit, CreditCardUsage, CreditUtilization, TransactionsPerMonth, OnlineTransactions, ATMWithdrawals, LatePayments, MissedEMIs, BankBalance, PropertyValue, Dependents, Region, CityTier, PreviousDefaults, FraudFlag, CustomerSegment, LoanApproved]
Index: []

[0 rows x 34 columns]

In [11]:
df[df["CreditScore"] > 900]

,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,Savings,...,MissedEMIs,BankBalance,PropertyValue,Dependents,Region,CityTier,PreviousDefaults,FraudFlag,CustomerSegment,LoanApproved
136,103705,33,Female,Single,Graduate,SelfEmployed,8.0,NaN,117347,507314.0,...,0,545001.0,5143951.0,0,South,Tier3,0,No,Regular,Yes
224,105655,30,Female,Married,HighSchool,Salaried,14.0,2154585.0,156532,1722219.0,...,1,1690722.0,40913261.0,0,North,Tier1,1,No,Regular,Yes
256,108616,26,Male,Married,PostGraduate,SelfEmployed,NaN,3952248.0,114531,9623800.0,...,0,1155534.0,47893324.0,5,East,Tier3,3,No,Regular,Yes
365,109721,32,Female,Married,PostGraduate,Salaried,34.0,4171604.0,18058,1443430.0,...,3,168997.0,15989548.0,5,North,Tier2,3,No,Regular,Yes
496,121706,34,Male,Married,Graduate,NaN,NaN,4655111.0,115381,1339424.0,...,3,1906160.0,18358161.0,1,South,Tier2,3,No,Regular,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24967,124276,33,Male,Married,PostGraduate,SelfEmployed,30.0,1879620.0,137004,5564828.0,...,3,1033709.0,4416575.0,1,North,Tier1,2,No,Regular,Yes
25337,118071,36,Male,Married,PostGraduate,Business,2.0,5794518.0,21593,6786948.0,...,1,1496429.0,1033764.0,1,North,Tier1,1,No,Premium,Yes
25361,111754,41,Male,Single,PostGraduate,Salaried,30.0,NaN,183789,4490084.0,...,2,1830994.0,34630406.0,3,East,Tier1,0,No,Regular,Yes
25374,123724,53,Female,Divorced,Graduate,Student,0.0,2056152.0,173445,3294377.0,...,3,1949618.0,39847763.0,3,South,Tier3,3,Yes,Risky,No
25384,109152,26,Male,Married,Graduate,Salaried,23.0,2263101.0,189872,8458413.0,...,3,712231.0,37913442.0,3,West,Tier1,0,No,Premium,Yes

In [14]:
median_credit = df[df["CreditScore"] <= 900]["CreditScore"].median()

df.loc[df["CreditScore"] > 900,"CreditScore"] = median_credit

In [15]:
df[df["CreditScore"]> 900]

Empty DataFrame
Columns: [CustomerID, Age, Gender, MaritalStatus, Education, Occupation, EmploymentYears, AnnualIncome, MonthlyExpenses, Savings, Investments, ExistingLoans, ExistingEMI, LoanAmount, LoanPurpose, LoanTenure, CreditScore, CreditCardLimit, CreditCardUsage, CreditUtilization, TransactionsPerMonth, OnlineTransactions, ATMWithdrawals, LatePayments, MissedEMIs, BankBalance, PropertyValue, Dependents, Region, CityTier, PreviousDefaults, FraudFlag, CustomerSegment, LoanApproved]
Index: []

[0 rows x 34 columns]

In [16]:
numeric_col = df.select_dtypes(include=["int64","Float64"]).columns
numeric_col

Index(['CustomerID', 'Age', 'EmploymentYears', 'AnnualIncome',
       'MonthlyExpenses', 'Savings', 'Investments', 'ExistingLoans',
       'ExistingEMI', 'LoanAmount', 'LoanTenure', 'CreditScore',
       'CreditCardLimit', 'CreditCardUsage', 'CreditUtilization',
       'TransactionsPerMonth', 'OnlineTransactions', 'ATMWithdrawals',
       'LatePayments', 'MissedEMIs', 'BankBalance', 'PropertyValue',
       'Dependents', 'PreviousDefaults'],
      dtype='str')

In [17]:
imputer = SimpleImputer(strategy="median")
df[numeric_col] = imputer.fit_transform(df[numeric_col])

In [18]:
categotical_col = df.select_dtypes(include="object").columns
categotical_col

C:\Users\Pranavraj\AppData\Local\Temp\ipykernel_18352\3449889671.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categotical_col = df.select_dtypes(include="object").columns

Index(['Gender', 'MaritalStatus', 'Education', 'Occupation', 'LoanPurpose',
       'Region', 'CityTier', 'FraudFlag', 'CustomerSegment', 'LoanApproved'],
      dtype='str')

In [19]:
cat_imputer = SimpleImputer(strategy="most_frequent")
df[categotical_col] = cat_imputer.fit_transform(df[categotical_col])

In [20]:
df.isnull().sum()

CustomerID              0
Age                     0
Gender                  0
MaritalStatus           0
Education               0
Occupation              0
EmploymentYears         0
AnnualIncome            0
MonthlyExpenses         0
Savings                 0
Investments             0
ExistingLoans           0
ExistingEMI             0
LoanAmount              0
LoanPurpose             0
LoanTenure              0
CreditScore             0
CreditCardLimit         0
CreditCardUsage         0
CreditUtilization       0
TransactionsPerMonth    0
OnlineTransactions      0
ATMWithdrawals          0
LatePayments            0
MissedEMIs              0
BankBalance             0
PropertyValue           0
Dependents              0
Region                  0
CityTier                0
PreviousDefaults        0
FraudFlag               0
CustomerSegment         0
LoanApproved            0
dtype: int64

In [21]:
print(df.shape)
df.info()

(25600, 34)
<class 'pandas.DataFrame'>
Index: 25600 entries, 0 to 25749
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerID            25600 non-null  float64
 1   Age                   25600 non-null  float64
 2   Gender                25600 non-null  str
 3   MaritalStatus         25600 non-null  str
 4   Education             25600 non-null  str
 5   Occupation            25600 non-null  str
 6   EmploymentYears       25600 non-null  float64
 7   AnnualIncome          25600 non-null  float64
 8   MonthlyExpenses       25600 non-null  float64
 9   Savings               25600 non-null  float64
 10  Investments           25600 non-null  float64
 11  ExistingLoans         25600 non-null  float64
 12  ExistingEMI           25600 non-null  float64
 13  LoanAmount            25600 non-null  float64
 14  LoanPurpose           25600 non-null  str
 15  LoanTenure            25600 non-null  float64
 16  CreditScore           25600 non-null  float64
 17  CreditCardLimit       25600 non-null  float64
 18  CreditCardUsage       25600 non-null  float64
 19  CreditUtilization     25600 non-null  float64
 20  TransactionsPerMonth  25600 non-null  float64
 21  OnlineTransactions    25600 non-null  float64
 22  ATMWithdrawals        25600 non-null  float64
 23  LatePayments          25600 non-null  float64
 24  MissedEMIs            25600 non-null  float64
 25  BankBalance           25600 non-null  float64
 26  PropertyValue         25600 non-null  float64
 27  Dependents            25600 non-null  float64
 28  Region                25600 non-null  str
 29  CityTier              25600 non-null  str
 30  PreviousDefaults      25600 non-null  float64
 31  FraudFlag             25600 non-null  str
 32  CustomerSegment       25600 non-null  str
 33  LoanApproved          25600 non-null  str
dtypes: float64(24), str(10)
memory usage: 6.8 MB

In [23]:
df.to_csv("../data/processed/loan_risk_dataset_clean.csv")