In [1]:
import pandas as pd
import joblib

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import AdaBoostClassifier

In [2]:
df = pd.read_csv("../data/processed/loan_risk_feature_engineered.csv")
df.head(10)

,Unnamed: 0,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,...,FraudFlag,CustomerSegment,LoanApproved,MonthlyIncome,DisposableIncome,EMIRatio,SavingRatio,DebtToIncomeRatio,Networth,CreditUtilizationRatio
0,0,112424.0,36.0,Male,Single,PostGraduate,Salaried,25.0,6114208.0,190034.0,...,No,Regular,No,509517.333333,319483.333333,0.037881,0.751028,0.587899,7316519.0,0.192366
1,1,108271.0,25.0,Female,Single,HighSchool,SelfEmployed,30.0,4487423.0,24602.0,...,No,Regular,Yes,373951.916667,349349.916667,0.109621,1.979788,0.273935,13485542.0,0.085016
2,2,122724.0,32.0,Male,Single,Graduate,SelfEmployed,8.0,7493921.0,60028.0,...,No,Regular,Yes,624493.416667,564465.416667,0.078643,0.555598,0.495641,10186747.0,0.070233
3,3,112573.0,30.0,Female,Married,Graduate,Student,35.0,4152555.0,187520.0,...,No,Regular,Yes,346046.250000,158526.250000,0.163487,2.337600,0.611959,14080359.0,0.116370
4,4,112098.0,41.0,Female,Single,Graduate,Business,36.0,7929802.0,199257.0,...,No,Regular,No,660816.833333,461559.833333,0.075230,0.006726,0.238586,1209057.0,0.237283
5,5,113701.0,35.0,Female,Divorced,Graduate,Salaried,3.0,6937350.0,232553.0,...,No,Premium,Yes,578112.500000,345559.500000,0.164537,0.426292,0.069782,5586075.0,0.042915
6,6,110753.0,43.0,Male,Married,Graduate,Business,29.0,4152555.0,96000.0,...,No,Regular,Yes,346046.250000,250046.250000,0.189388,0.690360,0.071387,4086926.0,0.003147
7,7,122123.0,29.0,Female,Divorced,Graduate,Student,11.0,868052.0,148148.0,...,No,Regular,No,72337.666667,-75810.333333,0.971679,0.009540,5.614350,5070760.0,0.247798
8,8,103275.0,61.0,Female,Married,HighSchool,Business,23.0,4152555.0,63060.0,...,No,Regular,Yes,346046.250000,282986.250000,0.328236,2.122930,0.124249,10103306.0,0.060935
9,9,102542.0,23.0,Male,Married,HighSchool,Salaried,20.0,3046784.0,66431.0,...,Yes,Risky,No,253898.666667,187467.666667,0.026897,0.594650,0.465842,6701641.0,0.273223

In [3]:
df = df.drop(columns=[
    "CustomerID",
    "FraudFlag",
    "CustomerSegment","Unnamed: 0"
])

In [4]:
label = LabelEncoder()

cat_cols = df.select_dtypes(include=["object", "string"]).columns

for col in cat_cols:
    df[col] = label.fit_transform(df[col])

X = df.drop(columns=["LoanApproved"])

y = df["LoanApproved"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
model = AdaBoostClassifier(
    random_state=42
)

model.fit(
    X_train,
    y_train
)

AdaBoostClassifier(random_state=42)

In [6]:
joblib.dump(model,"../models/adaboost_model.pkl")

['../models/adaboost_model.pkl']

In [7]:
loaded_model = joblib.load("../models/adaboost_model.pkl")

loaded_scaler = joblib.load(
    "../models/scaler.pkl"
)

In [8]:
sample = X.iloc[[0]]
sample

,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,Savings,Investments,...,Region,CityTier,PreviousDefaults,MonthlyIncome,DisposableIncome,EMIRatio,SavingRatio,DebtToIncomeRatio,Networth,CreditUtilizationRatio
0,36.0,1,2,3,2,25.0,6114208.0,190034.0,4591940.0,2645370.0,...,0,2,1.0,509517.333333,319483.333333,0.037881,0.751028,0.587899,7316519.0,0.192366

In [9]:
sample = loaded_scaler.transform(sample)

In [10]:
prediction = loaded_model.predict(sample)
print(prediction)

[0]

In [11]:
sample = X.iloc[[0]]

sample_scaled = loaded_scaler.transform(sample)

prediction = loaded_model.predict(sample_scaled)

probability = loaded_model.predict_proba(sample_scaled)

print("Prediction :", prediction[0])

print("Probability :", probability)

Prediction : 0
Probability : [[0.59126219 0.40873781]]

In [12]:
print(df.iloc[0][[
    "CreditScore",
    "LoanAmount",
    "PreviousDefaults",
    "ExistingLoans",
    "ExistingEMI",
    "LoanApproved"
]])

CreditScore             411.0
LoanAmount          3594536.0
PreviousDefaults          1.0
ExistingLoans             3.0
ExistingEMI           19301.0
LoanApproved              0.0
Name: 0, dtype: float64

In [13]:
print(probability)

[[0.59126219 0.40873781]]

In [14]:
if prediction[0] == 1:
    print("Loan Approved")

else:
    print("Loan Rejected")

Loan Rejected

In [15]:
probability = loaded_model.predict_proba(sample)
print(probability)

[[0.58913908 0.41086092]]

C:\Users\Pranavraj\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but AdaBoostClassifier was fitted without feature names
  warnings.warn(

In [16]:
batch = X.iloc[:10]
batch = loaded_scaler.transform(batch)
prediction = loaded_model.predict(batch)

prediction

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 0])

In [17]:
result = X.iloc[:10].copy()
result["Prediction"] = prediction

result.to_csv("../data/predictions.csv",index = False)

result.head()

,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,Savings,Investments,...,CityTier,PreviousDefaults,MonthlyIncome,DisposableIncome,EMIRatio,SavingRatio,DebtToIncomeRatio,Networth,CreditUtilizationRatio,Prediction
0,36.0,1,2,3,2,25.0,6114208.0,190034.0,4591940.0,2645370.0,...,2,1.0,509517.333333,319483.333333,0.037881,0.751028,0.587899,7316519.0,0.192366,0
1,25.0,0,2,1,3,30.0,4487423.0,24602.0,8884145.0,4084355.0,...,1,1.0,373951.916667,349349.916667,0.109621,1.979788,0.273935,13485542.0,0.085016,1
2,32.0,1,2,0,3,8.0,7493921.0,60028.0,4163611.0,4067065.0,...,0,0.0,624493.416667,564465.416667,0.078643,0.555598,0.495641,10186747.0,0.070233,1
3,30.0,0,1,0,4,35.0,4152555.0,187520.0,9707012.0,3460398.0,...,2,2.0,346046.250000,158526.250000,0.163487,2.337600,0.611959,14080359.0,0.116370,1
4,41.0,0,2,0,0,36.0,7929802.0,199257.0,53335.0,156887.0,...,1,2.0,660816.833333,461559.833333,0.075230,0.006726,0.238586,1209057.0,0.237283,0

In [21]:
importance = pd.DataFrame({
    "Feature":X.columns,
    "Importance":model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.to_csv("../data/feature_importance.csv",
                  index = False)

In [20]:
importance.head(15)

            Feature  Importance
23       MissedEMIs    0.224913
22     LatePayments    0.188875
15      CreditScore    0.184674
10    ExistingLoans    0.182479
30    MonthlyIncome    0.118376
6      AnnualIncome    0.100682
4        Occupation    0.000000
2     MaritalStatus    0.000000
1            Gender    0.000000
0               Age    0.000000
3         Education    0.000000
8           Savings    0.000000
7   MonthlyExpenses    0.000000
12       LoanAmount    0.000000
13      LoanPurpose    0.000000